### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by christhalinger** [twitter/twitter-server#39]
Here is what I get with the latest checkout:

```
$ ./sbt test
[info] Loading project definition from /Users/cthaling/twitter-server/project
[info] Set current project to twitter-server (in build file:/Users/cthaling/twitter-server/)
[info] Updating {file:/Users/cthaling/twitter-server/}twitter-server...
[info] Resolving com.twitter#finagle-core_2.11;6.34.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#finagle-core_2.11;6.34.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/finagle-core_2.11/6.34.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/finagle-core_2.11/6.34.0-SNAPSHOT/finagle-core_2.11-6.34.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/finagle-core_2.11/6.34.0-SNAPSHOT/finagle-core_2.11-6.34.0-SNAPSHOT.pom
[info] Resolving com.twitter#finagle-http_2.11;6.34.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#finagle-http_2.11;6.34.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/finagle-http_2.11/6.34.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/finagle-http_2.11/6.34.0-SNAPSHOT/finagle-http_2.11-6.34.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/finagle-http_2.11/6.34.0-SNAPSHOT/finagle-http_2.11-6.34.0-SNAPSHOT.pom
[info] Resolving com.twitter#finagle-zipkin_2.11;6.34.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#finagle-zipkin_2.11;6.34.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/finagle-zipkin_2.11/6.34.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/finagle-zipkin_2.11/6.34.0-SNAPSHOT/finagle-zipkin_2.11-6.34.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/finagle-zipkin_2.11/6.34.0-SNAPSHOT/finagle-zipkin_2.11-6.34.0-SNAPSHOT.pom
[info] Resolving com.twitter#util-app_2.11;6.33.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#util-app_2.11;6.33.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/util-app_2.11/6.33.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/util-app_2.11/6.33.0-SNAPSHOT/util-app_2.11-6.33.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/util-app_2.11/6.33.0-SNAPSHOT/util-app_2.11-6.33.0-SNAPSHOT.pom
[info] Resolving com.twitter#util-core_2.11;6.33.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#util-core_2.11;6.33.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/util-core_2.11/6.33.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/util-core_2.11/6.33.0-SNAPSHOT/util-core_2.11-6.33.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/util-core_2.11/6.33.0-SNAPSHOT/util-core_2.11-6.33.0-SNAPSHOT.pom
[info] Resolving com.twitter#util-events_2.11;6.33.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#util-events_2.11;6.33.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/util-events_2.11/6.33.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/util-events_2.11/6.33.0-SNAPSHOT/util-events_2.11-6.33.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/util-events_2.11/6.33.0-SNAPSHOT/util-events_2.11-6.33.0-SNAPSHOT.pom
[info] Resolving com.twitter#util-jvm_2.11;6.33.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#util-jvm_2.11;6.33.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/util-jvm_2.11/6.33.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/util-jvm_2.11/6.33.0-SNAPSHOT/util-jvm_2.11-6.33.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/util-jvm_2.11/6.33.0-SNAPSHOT/util-jvm_2.11-6.33.0-SNAPSHOT.pom
[info] Resolving com.twitter#util-lint_2.11;6.33.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#util-lint_2.11;6.33.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/util-lint_2.11/6.33.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/util-lint_2.11/6.33.0-SNAPSHOT/util-lint_2.11-6.33.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/util-lint_2.11/6.33.0-SNAPSHOT/util-lint_2.11-6.33.0-SNAPSHOT.pom
[info] Resolving com.twitter#util-logging_2.11;6.33.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#util-logging_2.11;6.33.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/util-logging_2.11/6.33.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/util-logging_2.11/6.33.0-SNAPSHOT/util-logging_2.11-6.33.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/util-logging_2.11/6.33.0-SNAPSHOT/util-logging_2.11-6.33.0-SNAPSHOT.pom
[info] Resolving com.twitter#util-registry_2.11;6.33.0-SNAPSHOT ...
[warn] 	module not found: com.twitter#util-registry_2.11;6.33.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/cthaling/.ivy2/local/com.twitter/util-registry_2.11/6.33.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/util-registry_2.11/6.33.0-SNAPSHOT/util-registry_2.11-6.33.0-SNAPSHOT.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/util-registry_2.11/6.33.0-SNAPSHOT/util-registry_2.11-6.33.0-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#finagle-core_2.11;6.34.0-SNAPSHOT: not found
[warn] 	:: com.twitter#finagle-http_2.11;6.34.0-SNAPSHOT: not found
[warn] 	:: com.twitter#finagle-zipkin_2.11;6.34.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-app_2.11;6.33.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-core_2.11;6.33.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-events_2.11;6.33.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-jvm_2.11;6.33.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-lint_2.11;6.33.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-logging_2.11;6.33.0-SNAPSHOT: not found
[warn] 	:: com.twitter#util-registry_2.11;6.33.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter:util-core_2.11:6.33.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:util-registry_2.11:6.33.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:finagle-zipkin_2.11:6.34.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:util-app_2.11:6.33.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:finagle-http_2.11:6.34.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:util-events_2.11:6.33.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:finagle-core_2.11:6.34.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:util-logging_2.11:6.33.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:util-lint_2.11:6.33.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
[warn] 		com.twitter:util-jvm_2.11:6.33.0-SNAPSHOT (/Users/cthaling/twitter-server/project/Build.scala#L116)
[warn] 		  +- com.twitter:twitter-server_2.11:1.19.0-SNAPSHOT ()
sbt.ResolveException: unresolved dependency: com.twitter#finagle-core_2.11;6.34.0-SNAPSHOT: not found
unresolved dependency: com.twitter#finagle-http_2.11;6.34.0-SNAPSHOT: not found
unresolved dependency: com.twitter#finagle-zipkin_2.11;6.34.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-app_2.11;6.33.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-core_2.11;6.33.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-events_2.11;6.33.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-jvm_2.11;6.33.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-lint_2.11;6.33.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-logging_2.11;6.33.0-SNAPSHOT: not found
unresolved dependency: com.twitter#util-registry_2.11;6.33.0-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (twitter-server/*:update) sbt.ResolveException: unresolved dependency: com.twitter#finagle-core_2.11;6.34.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#finagle-http_2.11;6.34.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#finagle-zipkin_2.11;6.34.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#util-app_2.11;6.33.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#util-core_2.11;6.33.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#util-events_2.11;6.33.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#util-jvm_2.11;6.33.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#util-lint_2.11;6.33.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#util-logging_2.11;6.33.0-SNAPSHOT: not found
[error] unresolved dependency: com.twitter#util-registry_2.11;6.33.0-SNAPSHOT: not found
[error] Total time: 6 s, completed Mar 31, 2016 4:11:17 PM
```

**Comment by vkostyukov** [comment]
Sorry for the confusion, @christhalinger. That's the tricky part of the developing workflow, our contributors have to deal with. You can have a look at the [contributor guide](https://github.com/twitter/twitter-server/blob/develop/CONTRIBUTING.md#building-dependencies) that explains how to build dependencies (TL;DT `TRAVIS_SCALA_VERSION=2.11.7 ./bin/travisci`).

**Comment by christhalinger** [comment]
Yes, it is confusing, to say the least.  Maybe a link to that paragraph in the README would be helpful.

**Comment by christhalinger** [comment]
After running your suggested command everything works fine.
