### ISSUE TITLE
NoClassDefFoundError: Could not initialize class com.twitter.server.util.JsonConverter

### ISSUE THREAD

**Issue by mikebridge** [twitter/twitter-server#45]
When I access the TwitterServer's admin interface (e.g. at [http://localhost:9990/admin/metrics](http://localhost:9990/admin/metrics)) I get a `NoClassDefFoundError`

### Expected behavior

Expected the stats to appear

### Actual behavior

Console repeatedly generates `java.lang.NoClassDefFoundError: Could not initialize class com.twitter.server.util.JsonConverter` plus a stack trace:

```
W 0824 15:11:06.000 THREAD74: Unhandled exception in connection with /127.0.0.1:54989 , shutting down connection
java.lang.NoClassDefFoundError: Could not initialize class com.twitter.server.util.JsonConverter$
	at com.twitter.server.handler.MetricQueryHandler.apply(MetricQueryHandler.scala:54)
	at com.twitter.server.handler.MetricQueryHandler.apply(MetricQueryHandler.scala:34)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.server.view.IndexView.apply(IndexView.scala:123)
	at com.twitter.server.view.IndexView.apply(IndexView.scala:114)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.http.HttpMuxer.apply(HttpMuxer.scala:62)
	at com.twitter.finagle.http.HttpMuxer.apply(HttpMuxer.scala:25)
	at com.twitter.server.util.HttpUtils$$anonfun$combine$1.com$twitter$server$util$HttpUtils$$anonfun$$loop$1(HttpUtils.scala:25)
	at com.twitter.server.util.HttpUtils$$anonfun$combine$1.apply(HttpUtils.scala:35)
	at com.twitter.server.util.HttpUtils$$anonfun$combine$1.apply(HttpUtils.scala:20)
	at com.twitter.finagle.Service$$anon$5.apply(Service.scala:28)
	at com.twitter.server.AdminHttpServer$$anon$1.apply(AdminHttpServer.scala:74)
	at com.twitter.server.AdminHttpServer$$anon$1.apply(AdminHttpServer.scala:73)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.server.view.NotFoundView.apply(NotFoundView.scala:41)
	at com.twitter.server.view.NotFoundView.apply(NotFoundView.scala:37)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.ServiceProxy.apply(Service.scala:120)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.tracing.ServerDestTracingProxy$$anon$1.apply(DestinationTracing.scala:32)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.service.DeadlineStatsFilter.apply(DeadlineStatsFilter.scala:59)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.ExceptionSourceFilter.apply(ExceptionSourceFilter.scala:42)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.filter.HttpNackFilter.apply(HttpNackFilter.scala:55)
	at com.twitter.finagle.http.filter.HttpNackFilter.apply(HttpNackFilter.scala:48)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:13)
	at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2$$anonfun$apply$3.apply(Codec.scala:476)
	at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2$$anonfun$apply$3.apply(Codec.scala:476)
	at com.twitter.finagle.http.TraceInfo$$anonfun$letTraceIdFromRequestHeaders$2.apply(Codec.scala:422)
	at com.twitter.util.Local.let(Local.scala:141)
	at com.twitter.finagle.context.Context$class.let(Context.scala:176)
	at com.twitter.finagle.context.MarshalledContext.let(Context.scala:232)
	at com.twitter.finagle.tracing.Trace$.letId(Trace.scala:167)
	at com.twitter.finagle.http.TraceInfo$.letTraceIdFromRequestHeaders(Codec.scala:420)
	at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2.apply(Codec.scala:476)
	at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2.apply(Codec.scala:476)
	at com.twitter.util.Local.let(Local.scala:141)
	at com.twitter.finagle.context.Context$class.let(Context.scala:176)
	at com.twitter.finagle.context.LocalContext.let(LocalContext.scala:8)
	at com.twitter.finagle.tracing.Trace$.letTracer(Trace.scala:185)
	at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8.apply(Codec.scala:475)
	at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8.apply(Codec.scala:474)
	at com.twitter.finagle.Filter$$anon$6.apply(Filter.scala:254)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.MonitorFilter.apply(MonitorFilter.scala:39)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.PayloadSizeFilter.apply(PayloadSizeFilter.scala:29)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.filter.ServerContextFilter$$anonfun$apply$1.apply(ContextFilter.scala:16)
	at com.twitter.finagle.http.filter.ServerContextFilter$$anonfun$apply$1.apply(ContextFilter.scala:16)
	at com.twitter.finagle.http.codec.HttpContext$.read(HttpContext.scala:52)
	at com.twitter.finagle.http.filter.ServerContextFilter.apply(ContextFilter.scala:16)
	at com.twitter.finagle.http.filter.ServerContextFilter.apply(ContextFilter.scala:12)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.filter.DtabFilter.apply(DtabFilter.scala:26)
	at com.twitter.finagle.http.filter.DtabFilter.apply(DtabFilter.scala:12)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:79)
	at com.twitter.finagle.http.codec.HttpServerDispatcher.dispatch(HttpServerDispatcher.scala:61)
	at com.twitter.finagle.http.codec.HttpServerDispatcher.dispatch(HttpServerDispatcher.scala:20)
	at com.twitter.finagle.http.exp.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$http$exp$GenSerialServerDispatcher$$loop$1$$anonfun$apply$1.apply$mcV$sp(ServerDispatcher.scala:55)
	at com.twitter.finagle.http.exp.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$http$exp$GenSerialServerDispatcher$$loop$1$$anonfun$apply$1.apply(ServerDispatcher.scala:54)
	at com.twitter.finagle.http.exp.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$http$exp$GenSerialServerDispatcher$$loop$1$$anonfun$apply$1.apply(ServerDispatcher.scala:54)
	at com.twitter.util.Local.let(Local.scala:141)
	at com.twitter.finagle.context.Context$class.let(Context.scala:176)
	at com.twitter.finagle.context.LocalContext.let(LocalContext.scala:8)
	at com.twitter.finagle.http.exp.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$http$exp$GenSerialServerDispatcher$$loop$1.apply(ServerDispatcher.scala:53)
	at com.twitter.finagle.http.exp.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$http$exp$GenSerialServerDispatcher$$loop$1.apply(ServerDispatcher.scala:48)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1092)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1091)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:436)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:201)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:159)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:239)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:107)
	at com.twitter.util.Promise.runq(Promise.scala:405)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:796)
	at com.twitter.util.Promise.update(Promise.scala:770)
	at com.twitter.util.Promise.setValue(Promise.scala:746)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:120)
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at com.twitter.finagle.http.SafeServerHttpChunkAggregator.handleUpstream(Codec.scala:101)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
	at com.twitter.finagle.http.codec.RespondToExpectContinue.messageReceived(RespondToExpectContinue.scala:30)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
	at com.twitter.finagle.http.codec.PayloadSizeHandler.messageReceived(PayloadSizeHandler.scala:22)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpServerCodec.handleUpstream(HttpServerCodec.java:56)
	at com.twitter.finagle.http.SafeHttpServerCodec.handleUpstream(Codec.scala:123)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)

```
### Steps to reproduce the behavior

Start the server and navigate to e.g. `http://localhost:9990/admin/metrics`

```scala
    val server = Http.server
      .withAdmissionControl.concurrencyLimit(
      maxConcurrentRequests = 10,
      maxWaiters = 10
    ).serve(":8081", api.toService)

    onExit {
      server.close()
    }

    Await.ready(adminHttpServer)
```

I'm using twitter-server 1.21.0 and finagle 6.36.0 (via finch 0.11.0-M2).

**Comment by kevinoliver** [comment]
My best guess is that you are missing a dependency on `finagle-stats`.

I _think_ this is covered in the [getting started section](http://twitter.github.io/twitter-server/#getting-started), but perhaps it needs some cleanup or polish?

**Comment by mikebridge** [comment]
@kevinoliver I added finagle-stats 6.36.0 but I'm still getting the error.

I can see that my installed version twitter-server has a version of `com.twitter.server.util.JsonConverter`.  I'm stepping through it with a debugger and it looks to me like it should work.  Hmm...

**Comment by mikebridge** [comment]
A closer examination of the logs shows that the Jackson version (pulled in transitively from Circe) is the issue: 

```
SEVERE: LoadService: failed to instantiate 'com.twitter.finagle.stats.MetricsExporter' for the requested service 'com.twitter.finagle.http.HttpMuxHandler'
com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.7.1
```

After it fails to load, then it starts spewing `java.lang.NoClassDefFoundError` into the logs.

**Comment by mikebridge** [comment]
Dunno if there's a more sbt-friendly way of doing this but this seems to work:

```scala
val jacksonV = "2.6.7"
val `jackson-core` = "com.fasterxml.jackson.core" % "jackson-core" % jacksonV
val `jackson-databind` = "com.fasterxml.jackson.core" % "jackson-databind" % jacksonV
val `jackson-annotations` = "com.fasterxml.jackson.core" % "jackson-annotations" % jacksonV
val `jackson-datatype-jsr310` = "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % jacksonV

dependencyOverrides += `jackson-core`
dependencyOverrides += `jackson-databind`
dependencyOverrides += `jackson-annotations`
dependencyOverrides += `jackson-datatype-jsr310`

libraryDependencies ++= Seq(
    `jackson-databind`,
    `jackson-core`,
    `jackson-annotations`,
    `jackson-datatype-jsr310`,
    // ...
)
```

**Comment by mosesn** [comment]
@mikebridge looks like you were able to figure out your problem, so I'm going to mark this as closed. 👍
